"""
Application Configuration
Generated by rag-ollama plugin
"""

from pydantic_settings import BaseSettings
from functools import lru_cache
from typing import Optional


class Settings(BaseSettings):
    """Application settings loaded from environment variables"""

    # Application
    APP_NAME: str = "{{PROJECT_NAME}}"
    ENVIRONMENT: str = "development"
    DEBUG: bool = True

    # Server
    HOST: str = "0.0.0.0"
    PORT: int = 8000

    # Ollama
    OLLAMA_BASE_URL: str = "http://localhost:11434"
    OLLAMA_MODEL: str = "{{LLM_MODEL}}"
    OLLAMA_EMBEDDINGS_MODEL: str = "{{EMBEDDINGS_MODEL}}"
    OLLAMA_TIMEOUT: int = 300

    # Qdrant
    QDRANT_HOST: str = "localhost"
    QDRANT_PORT: int = 6333
    QDRANT_COLLECTION: str = "{{PROJECT_NAME}}_vectors"

    # RAG Configuration
    CHUNK_SIZE: int = {{CHUNK_SIZE}}
    CHUNK_OVERLAP: int = {{CHUNK_OVERLAP}}
    RETRIEVAL_K: int = 5
    RETRIEVAL_STRATEGY: str = "{{RETRIEVAL_STRATEGY}}"
    SCORE_THRESHOLD: Optional[float] = None

    # Features
    ENABLE_USER_PROFILING: bool = {{ENABLE_PROFILING}}
    ENABLE_CITATIONS: bool = {{ENABLE_CITATIONS}}
    ENABLE_MULTIMODAL: bool = {{ENABLE_MULTIMODAL}}

    # Database (for conversation history)
    DATABASE_URL: str = "sqlite:///./data/app.db"

    # Security
    SECRET_KEY: str = "change-me-in-production"
    JWT_ALGORITHM: str = "HS256"
    JWT_EXPIRE_MINUTES: int = 60

    # Logging
    LOG_LEVEL: str = "INFO"
    LOG_FORMAT: str = "json"

    class Config:
        env_file = ".env"
        env_file_encoding = "utf-8"
        extra = "ignore"


@lru_cache()
def get_settings() -> Settings:
    """Get cached settings instance"""
    return Settings()
