"""
Main FastAPI Application
Generated by rag-ollama plugin
"""

from contextlib import asynccontextmanager
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import logging

from app.core.config import get_settings
from app.api.routes import chat, rag, health

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Application lifespan events"""
    settings = get_settings()
    logger.info(f"Starting {settings.APP_NAME}...")

    # Startup: Initialize services
    from app.services.ollama_service import get_ollama_service
    from app.services.qdrant_service import get_qdrant_service

    try:
        # Warmup Ollama
        ollama = get_ollama_service()
        await ollama.embed("warmup")
        logger.info("Ollama service ready")

        # Check Qdrant connection
        qdrant = get_qdrant_service()
        await qdrant.health_check()
        logger.info("Qdrant service ready")

    except Exception as e:
        logger.warning(f"Service warmup failed: {e}")

    yield

    # Shutdown
    logger.info("Shutting down...")


# Create app
settings = get_settings()

app = FastAPI(
    title=settings.APP_NAME,
    version="1.0.0",
    description="RAG API powered by Ollama, LangChain, and Qdrant",
    lifespan=lifespan
)

# CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Configure for production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Include routers
app.include_router(health.router, prefix="/api", tags=["health"])
app.include_router(chat.router, prefix="/api", tags=["chat"])
app.include_router(rag.router, prefix="/api", tags=["rag"])


@app.get("/")
async def root():
    return {
        "name": settings.APP_NAME,
        "version": "1.0.0",
        "docs": "/docs"
    }
